Rebrand (#57)
* Update 03-01-04-01-01-ipp.adoc

* Update 03-01-04-01-credit-card.adoc

* Update 03-01-04-01-credit-card.adoc

* Update 03-01-04-01-credit-card.adoc

* Update shortcuts.adoc

* Sepa CT changes for APMs and Diagram for cc payment

* Delete cc_dynamic-descriptor.png

* Add files via upload

* Update 02-general-integration-options.adoc

* General APM changes

* General APM changes

* Removed NVP Fields from the table

Removed NVP Fields from the table

* Removing NVP field

* Add files via upload

* Updated Image, Wirecard name removed

* Removed NVP examples and table values

* Cleanup Index for alipay

* removed WPPv1 reference

* remove wirecard

* remove wirecard

* Update build.yml

none: support for two AWS buckets

* Update build.yml

none: 2nd run of AWS change

* Update release.yml

none: updated AWS bucket for GN

* change font

* Update main.css

update with new santander css file

* Create main.css

update with new santander css file

* none: update of .gitignore

* Update shortcuts.adoc

'payment page anchor' static value fixed to Payment Page

* none: switched to GN

* none: resurected by comparing with master and adapting for GN

* Details of V1 are removed

* New theme checkout page

* Update 03-00-payment-page-solutions.adoc

* Update 03-00-payment-page-solutions.adoc

* Image updated

* Add files via upload

* Update 03-00-payment-page-solutions.adoc

* Delete Checkout GPP2.png

* Update 03-00-payment-page-solutions.adoc

* Update 03-00-payment-page-solutions.adoc

* NVP sample code removed

* NVP removed from table

* NVP field removed

* Update 03-01-06-05-max-retries.adoc

* NVP section removed

* Delete favicon.ico

will be replaced by the new favicon.ico file from Santander

* Delete favicon_256.png

will be replaced by favicon-256 file from Santander

* Add files via upload

new santander files

* Update 17-contact-us.adoc

update contact us

* Update 17-contact-us.adoc

update contact us

* Update 18-imprint.adoc

update imprint

* ideal and poipia updated

* Update 18-imprint.adoc

update imprint

* Update 18-imprint.adoc

update imprint

* sepa updated

* Update shortcuts.adoc

update naming & abbr

* paypal updated

* Update wd-payment-direct-debit-main.adoc

update name

* ideal updated

* Update wd-payment-invoice-main.adoc

update name

* Update wd-payment-invoice.adoc

replace getnet payment on invoice with Guaranteed Payment on invoice

* Update 08-02-ipn.adoc

IP updated

* Update 00-home.adoc

text update

* Update 02-general-integration-options.adoc

text update

* Update 03-01-01-01-hpp-integration-guide.adoc

remove getnet from text

* Update 03-01-02-01-epp-integration-guide.adoc

remove Getnet word

* Update 03-01-03-01-seamless-integration-guide.adoc

''by Getnet'' replaced with ''by us''

* Delete 03-01-01-02-hpp-with-nvp.adoc

* Delete 03-01-02-02-epp-with-nvp.adoc

* Update index.adoc

remove NVP in integration guide

* Delete 22-01-integration-guides-wppv2.adoc

* Update index.adoc

delete payment page level offset +1

* Update 03-01-wirecard-payment-page.adoc

* Update index.adoc

* Update release.yml

removed update of gh-pages

* none: update nokogiri due security findings on gh

* Revert "none: update nokogiri due security findings on gh"

This reverts commit 97be92da

* removed PP1 link in 3Ds2

* Update wd-payment-direct-debit.adoc

* none: fixed error of asciidoctor:
ERROR: index.adoc: line 34: include file not found: content/index/integration-options/09-shop-systems.adoc

* Delete 08-10-surcharging.adoc

* Update index.adoc

* none: droped /ppv1 references

* none: droped /mobile-payment-sdk references

* Delete 10-reporting.adoc

* Update index.adoc

* Update wd-payment-direct-debit.adoc

* Update wd-payment-direct-debit.adoc

* Changed image file extension

* Trying to make image work

* Update 03-00-payment-page-solutions.adoc

* Update 03-00-payment-page-solutions.adoc

* Update 03-00-payment-page-solutions.adoc

* Update 03-00-payment-page-solutions.adoc

* Update 03-00-payment-page-solutions.adoc

* WD logo removed

* WD logo removed

* WD logo removed

* ratepay direct debit updated

* Update 03-00-payment-page-solutions.adoc

* Delete Checkout_GPP2.png

* Add files via upload

* Payment Page image updated to new design

* ratepay direct debit updated

* ratepay direct debit updated

* ratepay direct debit updated

* ratepay direct debit updated

* Update shortcuts.adoc

* Update 11-01-credit-card.adoc

UPDATE TEST CREDENTIALS

* Update 11-01-credit-card.adoc

* Update 03-01-04-01-credit-card.adoc

* Update 11-01-08-testcards.adoc

remove test cards diners, JCB, UPI

* ratepay invoice updated

* alipay getnet domain name

* updated for NVP, added paypal credentials

* added paypal credentials

* added paypal credentials

* Features updated and table removed

* Update 03-00-payment-page-solutions.adoc

* Update 03-00-payment-page-solutions.adoc

* Update 00-home.adoc

* remove wirecard

* remove wirecard

* remove wirecard

* remove wirecard

* remove wirecard

* remove wirecard

* remove wirecard

* remove wirecard

* Update 11-01-credit-card.adoc

* remove wirecard

* remove wirecard

* Update 3-d-secure_testcards_success.adoc

* Update shortcuts.adoc

* Update 03-01-04-01-credit-card.adoc

* Update shortcuts.adoc

* Update 11-02-alipay-cross-border.adoc

* Update 03-01-04-02-alipay-cross-border.adoc

* remove wirecard

* acs url changed

* acs url changed to getnet

* Changed acs url to getnet

* Update 18-imprint.adoc

* Update 11-12-ideal.adoc

* Update 03-01-04-05-ideal.adoc

* Update 11-24-paypal.adoc

* remove wirecard

* Update 03-01-04-07-paypal.adoc

* Update 11-22-poipia.adoc

* Update 11-29-01-sepa-credit-transfer.adoc

* Update 03-01-04-10-sepa-direct-debit.adoc

* Update 11-31-sofort.adoc

* Update 03-01-04-11-sofort.adoc

* Delete visa-checkout-main.adoc

* Delete 11-35-visa-checkout.adoc

* Update index.adoc

* Update wd-payment-direct-debit.adoc

* Update wd-payment-direct-debit.adoc

* Update wd-payment-installment.adoc

* Update wd-payment-installment.adoc

* Update wd-payment-invoice.adoc

* Update 11-29-02-sepa-direct-debit.adoc

* remove wirecard

* remove wirecard

* Update wd-payment-direct-debit.adoc

* Update 11-31-sofort.adoc

* Update wd-payment-direct-debit.adoc

* Update wd-payment-installment.adoc

* Update wd-payment-installment.adoc

* Update wd-payment-invoice.adoc

* Update wd-payment-invoice.adoc

* Update 03-01-01-01-hpp-integration-guide.adoc

* Update 03-01-02-01-epp-integration-guide.adoc

* Update 03-01-03-01-seamless-integration-guide.adoc

* remove wirecard

* Update 3-d-secure_testcredentials_manual.adoc

* added terms and conditions

* Update 3-d-secure_testcredentials_automatic.adoc

* Update 3-d-secure-testing.adoc

* Update 3-d-secure-testing.adoc

* Update device-fingerprint.adoc

* Update wd-fraud-prevention-suite.adoc

* Update 17-contact-us.adoc

* added terms and conditions

* added terms and conditions

* Update 04-00-rest-api.adoc

* Update 03-01-03-01-seamless-integration-guide.adoc

* Update 03-01-04-01-credit-card.adoc

* Update 11-01-01-01-credit-card_transaction-types_authorization.adoc

* Update 11-01-01-02-credit-card_transaction-types_capture-authorization.adoc

* none: droped /batch-processing references

* none: dropped /multi-payment-api references

* none: dropped /changelog references

* none: dropped /demo-shop references

* none: fixed paypal references

* none: fixed paypal references

* none: fixed EBA references

* Update 11-01-01-03-credit-card_transaction-types_purchase.adoc

* none: fixed payment-page-anchor

* Update device-fingerprint.adoc

* Update ssl-certificates.adoc

* Update 03-01-04-01-credit-card.adoc

* Update device-fingerprint.adoc

* Update 3-d-secure-2-exemption-adviser.adoc

* Update 03-01-06-08-customized-display-text.adoc

* Update pm-filter-order.adoc

* replaced wirecard tech with getnet

* replaced wirecard tech with getnet

* replaced wirecard tech with getnet

* replaced wirecard with getnet

* Update ssl-certificates.adoc

* Update ssl-certificates.adoc

* Delete 3-d-secure-2-exemption-adviser.adoc

* Update index.adoc

* none: fixed -Manager anchor

* Update 16-07-appendix-k.adoc

* removed wirecard from the image

* Update 17-contact-us.adoc

* Update shortcuts.adoc

* Update 03-01-04-01-credit-card.adoc

* Update 18-imprint.adoc

* Update 17-contact-us.adoc

* Update 18-imprint.adoc

* Update 11-01-credit-card.adoc

* Update 03-01-04-01-credit-card.adoc

* Update WPP_FeaturesLimitCardbrandConfiguringLimitCardbrand_ExampleRequestLimitCardbrand.json

* Update cc-limit-card-brands.adoc

* Update 00-home.adoc

* Update 00-home.adoc

Co-authored-by: egorkosilkin <82930252+egorkosilkin@users.noreply.github.com>
Co-authored-by: Vinay Jain <vinay.jain@wirecard.com>
Co-authored-by: Muhammad Omer Qureshi <82945721+muhammad-qureshi@users.noreply.github.com>
Co-authored-by: comanl <comanl@users.noreply.github.com>
Co-authored-by: Liviu Coman <liviu.coman@getneteurope.com>